Repository Arquisoft/lomap_en2a, pull requests merged in 2023-04, with the labels that each got.

#103 Review + Scores functionality
  restapi/locations/Location.ts
  webapp/src/App.tsx
  webapp/src/components/Friends.tsx
  webapp/src/components/LocationInfo.tsx
  webapp/src/components/Menu.tsx
  webapp/src/components/ProfileInfo.tsx
  webapp/src/components/Review.tsx
  webapp/src/components/login/Login.tsx
  webapp/src/index.tsx
  webapp/src/solid/solidManagement.ts
Labels: 🔼enhancement, 🔠implementation

#148 Bug fix date reviews
  webapp/package-lock.json
  webapp/src/components/friends/Friends.tsx
  webapp/src/components/locations/LocationInfo.tsx
  webapp/src/components/locations/Review.tsx
  webapp/src/components/map/Map.tsx
  webapp/src/solid/solidManagement.ts
  webapp/src/tests/LocationInfo.test.tsx
  webapp/src/tests/Review.test.tsx
  webapp/src/types/types.tsx
Labels: 🕷️bug

#151 New login button and menu closed when unhover
  webapp/src/components/locations/AddLocationForm.tsx
  webapp/src/components/login/Login.tsx
  webapp/src/components/menu/Menu.tsx
Labels: 🔼enhancement

#157 Beutify location list
  webapp/env.local.download
  webapp/package-lock.json
  webapp/src/App.tsx
  webapp/src/components/dialogs/DeletingAlertDialog.tsx
  webapp/src/components/friends/Friends.tsx
  webapp/src/components/locations/AddLocationForm.tsx
  webapp/src/components/locations/CategoriesBubbles.tsx
  webapp/src/components/locations/ListOfLocations.tsx
  webapp/src/components/locations/LocationCard.tsx
  webapp/src/components/locations/LocationInfo.tsx
  webapp/src/components/locations/Review.tsx
  webapp/src/components/login/Login.tsx
  webapp/src/components/map/Map.tsx
  webapp/src/components/menu/Menu.tsx
  webapp/src/solid/solidManagement.ts
  webapp/src/tests/List.test.tsx
  webapp/src/tests/LocationInfo.test.tsx
  webapp/src/tests/Menu.test.tsx
  webapp/src/tests/Review.test.tsx
  webapp/src/types/types.tsx
Labels: 🔼enhancement

#156 Gamification features
  webapp/src/components/game/GamePanel.tsx
  webapp/src/components/locations/AddLocationForm.tsx
  webapp/src/components/locations/LocationInfo.tsx
  webapp/src/components/menu/Menu.tsx
Labels: 🔼enhancement, 🔠implementation

#170 Add location button on corner
  webapp/package-lock.json
  webapp/src/App.tsx
  webapp/src/components/dialogs/DeletingLocationAlertDialog.tsx
  webapp/src/components/friends/Friends.tsx
  webapp/src/components/game/GamePanel.tsx
  webapp/src/components/locations/AddLocationForm.tsx
  webapp/src/components/locations/CategoriesBubbles.tsx
  webapp/src/components/locations/ListOfLocations.tsx
  webapp/src/components/locations/LocationCard.tsx
  webapp/src/components/locations/LocationInfo.tsx
  webapp/src/components/locations/Review.tsx
  webapp/src/components/map/Map.tsx
  webapp/src/components/menu/Menu.tsx
  webapp/src/components/profile/ProfileInfo.tsx
  webapp/src/solid/solidManagement.ts
  webapp/src/tests/List.test.tsx
  webapp/src/tests/LocationCard.test.tsx
  webapp/src/tests/Map.test.tsx
  webapp/src/tests/Menu.test.tsx
  webapp/src/tests/Review.test.tsx
Labels: 🔼enhancement, 🔠implementation

#166 Cucumber tests + fixed percentage bug on game panel
  env.local
  webapp/e2e/features/add-friend.feature
  webapp/e2e/features/add-location.feature
  webapp/e2e/features/game.feature
  webapp/e2e/features/menu.feature
  webapp/e2e/features/profile.feature
  webapp/e2e/features/register-form.feature
  webapp/e2e/steps/add-friend.steps.ts
  webapp/e2e/steps/add-location.steps.ts
  webapp/e2e/steps/game.steps.ts
  webapp/e2e/steps/menu.steps.ts
  webapp/e2e/steps/profile.steps.ts
  webapp/e2e/steps/register-form.steps.ts
  webapp/src/components/dialogs/DeletingLocationAlertDialog.tsx
  webapp/src/components/game/GamePanel.tsx
  webapp/src/components/locations/AddLocationForm.tsx
  webapp/src/components/menu/Menu.tsx
  webapp/src/solid/solidManagement.ts
Labels: 👁️‍🗨️test
