Repository Arquisoft/lomap_en2a, pull requests merged in 2023-03, with the labels that each got.

#59 React map addition
  package-lock.json
  package.json
  restapi/locations/Location.ts
  restapi/locations/LocationController.ts
  restapi/locations/locationRoutes.ts
  restapi/maps/Map.ts
  restapi/maps/mapController.ts
  restapi/maps/mapRoutes.ts
  restapi/server.ts
  restapi/users/User.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/EmailForm.test.tsx
  webapp/src/components/EmailForm.tsx
  webapp/src/components/List.tsx
  webapp/src/components/Map.tsx
  webapp/src/components/PlaceDetail.tsx
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/components/Welcome.test.tsx
  webapp/src/components/Welcome.tsx
Labels: 🔼enhancement

#60 Menu adition
  restapi/api.ts
  restapi/maps/Map.ts
  restapi/maps/mapController.ts
  restapi/maps/mapRoutes.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/List.tsx
  webapp/src/components/Map.tsx
  webapp/src/components/Menu.tsx
Labels: 🔼enhancement

#52 Pod basic operations
  restapi/locations/Location.ts
  restapi/locations/LocationController.ts
  restapi/locations/locationRoutes.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/solidUtils/solidApi.ts
  restapi/solidUtils/solidManagement.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/List.tsx
  webapp/src/components/Menu.tsx
  webapp/src/components/locations/add/CreateLocation.tsx
  webapp/src/components/login/Login.tsx
  webapp/src/index.tsx
  webapp/src/solid/solidManagement.ts
  webapp/tsconfig.json
Labels: 🔼enhancement

#62 Friend list functionality (prototype, still not checking if valid WebID)
  restapi/users/User.ts
  webapp/src/App.tsx
  webapp/src/components/Friends.tsx
  webapp/src/components/FriendsDetail.tsx
  webapp/src/components/Menu.tsx
  webapp/src/solid/solidManagement.ts
Labels: 🔠implementation

#64 Santi adding new locations
  restapi/package-lock.json
  restapi/server.ts
  restapi/solidUtils/solidManagement.ts
  restapi/tests/api.test.ts
  webapp/src/App.tsx
  webapp/src/components/AddLocationForm.tsx
  webapp/src/components/Map.tsx
  webapp/src/components/Menu.tsx
Labels: 🔼enhancement

#65 Release 1.0 - prototype
  package-lock.json
  package.json
  restapi/api.ts
  restapi/locations/Location.ts
  restapi/locations/LocationController.ts
  restapi/locations/locationRoutes.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/solidUtils/solidApi.ts
  restapi/solidUtils/solidManagement.ts
  restapi/tests/api.test.ts
  restapi/users/User.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/AddLocationForm.tsx
  webapp/src/components/EmailForm.test.tsx
  webapp/src/components/EmailForm.tsx
  webapp/src/components/Friends.tsx
  webapp/src/components/FriendsDetail.tsx
  webapp/src/components/List.tsx
  webapp/src/components/LocationInfo.tsx
  webapp/src/components/Map.tsx
  webapp/src/components/Menu.tsx
  webapp/src/components/PlaceDetail.tsx
  webapp/src/components/ProfileInfo.tsx
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/components/Welcome.test.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/components/locations/add/CreateLocation.tsx
  webapp/src/components/login/Login.tsx
  webapp/src/index.tsx
  webapp/src/lomap_logo.png
  webapp/src/solid/solidManagement.ts
  webapp/tsconfig.json
Labels: 🔠implementation

#46 Fixed recommendations from the teachers.
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/images/10-Quality-MindMap.png
Labels: 🕷️bug, 📖documentation, ❓question

#90 Storing in private folder inside pod + storing images
  .github/workflows/ci.yml
  .github/workflows/lomap_en2a.yml
  README.md
  restapi/package-lock.json
  restapi/solidUtils/solidManagement.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/AddLocationForm.tsx
  webapp/src/components/Friends.tsx
  webapp/src/components/List.tsx
  webapp/src/components/LocationInfo.tsx
  webapp/src/components/Map.tsx
  webapp/src/components/Menu.tsx
  webapp/src/components/PlaceDetail.tsx
  webapp/src/components/ProfileInfo.tsx
  webapp/src/solid/solidManagement.ts
  webapp/tsconfig.json
Labels: 🕷️bug, 🔼enhancement, 🔠implementation

#94 Fix location description and beutified the location info window
  webapp/package.json
  webapp/src/api/api.ts
  webapp/src/components/LocationInfo.tsx
  webapp/src/components/PlaceDetail.tsx
  webapp/src/components/Review.tsx
  webapp/theme.js
Labels: 🕷️bug, 🔼enhancement

#97 Location list add image
  webapp/src/components/List.tsx
  webapp/src/components/LocationInfo.tsx
  webapp/src/components/PlaceDetail.tsx
  webapp/src/no-pictures-picture.png
Labels: 🔼enhancement
